version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs
            echo "--------- The images is Building ------------"
            docker build -t udagram-project-api-feed ./udagram-project-api-feed
            docker tag udagram-project-api-feed kabeer275/udagram-project-api-feed:v3
            docker build -t udagram-project-api-user ./udagram-project-api-user
            docker tag udagram-project-api-user kabeer275/udagram-project-api-user:v3
            
            docker build -t udagram-project-frontend ./udagram-project-frontend
            docker tag udagram-project-frontend kabeer275/udagram-project-frontend:v3
            docker build -t udagram-project-reverseproxy ./udagram-project-reverseproxy
            docker tag udagram-project-reverseproxy kabeer275/udagram-project-reverseproxy:v3
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u kabeer275 -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push kabeer275/udagram-project-api-feed:v3
            docker push kabeer275/udagram-project-api-user:v3
            docker push kabeer275/udagram-project-frontend:v3
            docker push kabeer275/udagram-project-reverseproxy:v3
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
